blank_issues_enabled: false
contact_links:
  - name: Pertanyaan Umum
    url: https://github.com/AlfarabiPratama/Clo-Visual/discussions
    about: Gunakan Discussions untuk tanya jawab non-bug / non-fitur.
